version: "3"

services:
  i4insdemo:
    build:
      context: .
    container_name: i4insdemo
    image: asolodkov/i4insdemo
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3002
    volumes:
      - ./logs:/logs
    networks:
      - i4insdemo-network
    ports:
      - 3002:3002

networks:
  i4insdemo-network:
    driver: bridge
